remote_theme: pmarsceill/just-the-docs
title: CISSP Zero to Hero
description: Ultimate CISSP Knowledge Base

# The "Nuclear Option" to ignore filename errors
excerpt_separator: ""
future: true
strict_front_matter: false

# Enable Search
search_enabled: true
search_tokenizer_separator: /[\s\-/]+/

# This tells Jekyll to ignore the system that is currently crashing
plugins:
  - jekyll-remote-theme
